require("plugins.lazy")

require("plugins.cmp")
require("plugins.debug.init")
require("plugins.fugitive")
require("plugins.mason")
require("plugins.null-ls")
require("plugins.rest")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.undotree")
require("plugins.vim_test")
