require("plugins.lazy")

require("plugins.cmp")
require("plugins.debug.init")
require("plugins.fugitive")
require("plugins.mason")
require("plugins.neodev")
require("plugins.conform")
require("plugins.nvim-lint")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.undotree")
require("plugins.vim_test")
